### ISSUE TITLE
PyPI release missing source code modules

### ISSUE THREAD

**Issue by PenutChen** [gradio-app/trackio#101]
**Describe the bug**
The PyPI distribution for trackio v0.2.1 (both the source tarball and the wheel) only includes documentation files (e.g. README.md, LICENSE, pyproject.toml) but none of the actual Python modules under the `trackio/` directory.

**To Reproduce**
1. Run `pip install trackio==0.2.1`
2. Inspect the installed package directory, e.g. `site-packages/trackio/`
3. Observe that only `README.md` (and metadata files) are present; no `.py` modules are installed.

**Expected behavior**
The installed package should include all Python source files (`*.py`) from the `trackio/` directory so that `import trackio` and its submodules work as intended.

**Actual behavior**
Only documentation and metadata are packaged. Attempting `trackio.init()` raises `AttributeError: module 'trackio' has no attribute 'init'`.

**Environment:**
- OS: Ubuntu 24.04
- Python version: 3.12.11
- pip version: 25.1

**Additional context**
The repository’s `trackio/` directory on GitHub does contain the Python modules, so it appears the packaging configuration (e.g. `pyproject.toml` or `MANIFEST.in`) is missing those files. Could you please update the packaging settings to include the source code in the next release?

**Comment by znation** [comment]
I can confirm it's broken in current main. Seems to have been broken by #75 -- I tried reverting that change locally and it produces a correct source distribution.
